travis:
  secure:
    BINSTAR_TOKEN: lI9aBfyxutnGHZGdb/gwmvwgm7uWRnxk8iZzMNVfWxtm9boWIaPskMGg7xmortOy7mSL60OGu+lO6mKPX+e2HdYinmPBxo93OfFFcNS8HAucszDDx0Mwacv8HTg1Rn5MGayCE9Lxi9bN06Nx2XOebDB/53ubjoJyNXJ6UVX9Qd2hxh4UAJp7NQSoaA1YEOEUOhwuhtEe12Bni9eeXUhr57jw4JGkCmE0t3MOVQd24KG4TCdeB2J5EGmycrsCHM1NIAIPh1iziUywO6oxf5eoE5rx3bysNB8jJyVQ5vZz58LE+SaO7F+f6IiFWVGxG46G0yCt4aK6+WqsWyWw2ZOddjMpxZu2j9pPK+vwymFTfCl7Rg8Cei9ynz6607/3gS0hc+BLUvhKWl3bitZNv8iVeAObT94S/L/b1skARBWshfKk8WpJPFdjCDiXAyRajlLIVjAnYseDUNM1lxu5STPQNayW/c+KIIez9YZNeeQXO/Vpmk3VLDMCbFX600JLKAqX/+xn4aULH+iryuBk7frHP5eXWLE5/RC71ve4gVNxL2O99wP5HUxROuGZzt6fKrHStv+555aMM6hJC1SCdQYkCH4i9yU/q5UAK5xUjSKBj18iD+B8r+TyH1Z9rhtR5GSLWPaEWWsLmsu38QOZxXCzaI948bei7FqgZccRO9dRu9Q=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
